### ISSUE TITLE
Training error - ValueError: 'default' must be a list when 'multiple' is true.

### ISSUE THREAD

**Issue by tribeband** [lukasruff/Deep-SVDD-PyTorch#40]
Traceback (most recent call last):
  File "d:\gitdownload\TS\Anomaly_detection\Deep-SVDD-PyTorch\src\main.py", line 56, in <module>
    def main(dataset_name, net_name, xp_path, data_path, load_config, load_model, objective, nu, device, seed,
  File "C:\Users\PC\.conda\envs\TS\lib\site-packages\click\decorators.py", line 373, in decorator
    _param_memo(f, cls(param_decls, **attrs))
  File "C:\Users\PC\.conda\envs\TS\lib\site-packages\click\core.py", line 2536, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "C:\Users\PC\.conda\envs\TS\lib\site-packages\click\core.py", line 2151, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.

will you please help on this?

**Comment by AlejandraM97** [comment]
I have the same error! Do you know why it appears? It would be very helpful!

**Comment by saharlynds** [comment]
instead of default=0 you should use default = [0], the error will be fixed!
